<?php

namespace LogManBundle\Repository;

/**
 * LogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends \Doctrine\ORM\EntityRepository {

    /**
     * 
     * @param type $dateA
     * @param type $dateB
     * @return type
     */
    public function getTotalByDate($dateA, $dateB) {

        $qb = $this->createQueryBuilder('p')
                ->select('count(p.sessionId) as total, p.status')
                ->where('p.datetime >= :dateStart')
                ->andWhere('p.datetime <= :dateEnd')
                ->setParameter('dateStart', $dateA)
                ->setParameter('dateEnd', $dateB)
                // ->groupBy('p.sessionId')
                ->GroupBy('p.status')
        //->groupBy('sessionId')
        ;

        return $qb->getQuery()->getResult();
    }

    public function checkUnique($date, $status, $sessionid) {


        $qb = $this->createQueryBuilder('p')
                ->select('count(p.id) as total')
                ->where('p.datetime = :date')
                ->andWhere('p.status = :dateEnd')
                ->andWhere('p.sessionId = :sessionId')
                ->setParameter('date', $date)
                ->setParameter('status', $status)
                ->setParameter('sessionId', $sessionid)
        ;

        $result = $qb->getQuery()->getOneOrNullResult();

        if ($result['total'] > 0) {
            return true;
        } else {
            return false;
        }
    }

}
